blank_issues_enabled: false
contact_lniks:
 - name: Discord Community Support
   url: https://discord.gg/tmodloader
   about: Please direct any and all help requests to here. If a help request is on Github, it WILL go unanswered