name: Preview tModLoader

# Controls when the action will run. 
on:
  # This workflow runs when a push to 1.4 branch happens, or when a label is added to a pull request targetting 1.4 branch.
  push:
    branches: [1.4-dev]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  MergeToPreview:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Make sure not to run this job on other labels
    if: github.event_name == 'push' && github.ref == 'refs/heads/1.4-dev'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Get current day
            id:day
            run: echo "::set-output name=date::$(date +'%d')"
        
        - name: Check out base branch
            if: ${{ steps.date.outputs.date }}<20
            uses: actions/checkout@v2
            with:
              persist-credentials: false
              fetch-depth: 10
          
        - name: Merge
            if: ${{ steps.date.outputs.date }}<20
            uses: robotology/gh-action-nightly-merge@v1.3.1
            with:
                stable_branch: '1.4-dev'
                development_branch: '1.4-preview'
                allow_ff: true
                ff_only: true
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}