name: Build tModLoader

# Controls when the action will run. 
on:
  # This workflow runs when a push to 1.4 branch happens, or when a label is added to a pull request targetting 1.4 branch.
  push:
    branches: [1.4-dev, 1.4-preview, 1.4-stable]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Make sure not to run this job on other labels

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      